
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: grasprails
  password: grasp-dev

development:
  <<: *default
  database: grasp_development
test:
  <<: *default
  database: grasp_test

production:
  <<: *default
  database: grasp_production
  
